### ISSUE TITLE
Implement section data components

### ISSUE THREAD

**Issue by keithradford** [VikeLabs/clockwork#16]
![Screen Shot 2021-02-24 at 6.00.09 PM.png](https://images.zenhubusercontent.com/5f973f7c87cad5309bf82827/4f329fe7-babb-4ea0-a971-2d50cae14a33)

[Figma](https://www.figma.com/file/taMF1mrqs7jAS7myzk78mT/clockwork?node-id=0%3A1)

---

We need a component to hold section data to make it look nice in the course content container.

Functionality:

- [ ] should take in an **icon**, **value (text)**, and a **colour** as props. (i.e. Calendar icon, "M, Th", and blue)
  - this is data that will be fetched from the outside, this component doesn't need to worry about API calls or fetching data.
  - could also pass a **name** as a prop instead of an **icon**, i.e. pass "times" and the logic in the component will know to use the clock icon. Whatever makes more sense.

Style:

- [ ] see screenshot above
  - if you feel any changes may look better, feel free to apply them.
- [ ] can just be a simple box component
- [ ] drop shadow

_everything above can be treated as tentative, feel free to make changes you view as necessary in development_

**Comment by shergillmanav19** [comment]
Aomi wants some changes to this and he currently has an idea that he's been working on so i will unassign myself from this. I might take over from his work but not too sure yet
