### ISSUE TITLE
Add hours field into course details response

### ISSUE THREAD

**Issue by aomi** [VikeLabs/clockwork#53]
Add the `hours` field into the course details response.

This involves updating the scraper library version in the dependencies and adding another "badge" to the frontend code.

**Comment by chsunwoo1002** [comment]
hours field is about "hoursCatalogText":"3-0-0" from Kuali course info?

**Comment by chsunwoo1002** [comment]
hours field is about "hoursCatalogText":"3-0-0" which is implemented in Course.tsx?

**Comment by aomi** [comment]
@chsunwoo1002 yup but it doesn't render as it's never passed any data from the API (it's an optional prop so it doesn't render). The backend API doesn't return it at the moment so we would need to update the backend then update the frontend to load the data and pass it into `Course.tsx` properly.

**Comment by chsunwoo1002** [comment]
@aomi thanks for the explanation!
