### ISSUE TITLE
Bookmarking course should save course to local storage

### ISSUE THREAD

**Issue by isaaccormack** [VikeLabs/clockwork#75]
When a user bookmarks a course, the course should be saved to [local browser storage](https://www.robinwieruch.de/local-storage-react) so the bookmarked courses can be persisted between browser sessions, without the user needing an account. It would be nice if there was a button to clear all bookmarked courses also developed for this issue. There should be an option to hide this button on the UI so we can turn it off in the staging env. Maybe the button would just go in the navbar for now.

Off the top of my head, a simple way to implement this would be to store an array of bookmarked courses in local storage. Each course in this array can be indexed on its term, subject, and code.

**Comment by keithradford** [comment]
@isaaccormack I believe issue #57 is the same as this. Maybe leave your comment there and we can close this, or close the old one and put this in the epic.

**Comment by isaaccormack** [comment]
Ahh didn't see those, thanks. Ill close those in favour of this as this is more descriptive IMO
