### ISSUE TITLE
Timetable waitlist seats are incorrect on course.

### ISSUE THREAD

**Issue by zthh626** [VikeLabs/clockwork#79]
Seats available are 44/45 but waitlist seats are 10/10. It should 45/45 or red because they're not able to sign up for the course.

![Screen Shot 2021-03-21 at 11.59.07 AM.png](https://images.zenhubusercontent.com/601f01cd32f8265c53ce4fad/178671ce-6b5c-4221-9555-2be0fe4e37b6)

![Screen Shot 2021-03-21 at 12.01.04 PM.png](https://images.zenhubusercontent.com/601f01cd32f8265c53ce4fad/d70d029a-3258-4a12-86c8-2b1cea95644c)

**Comment by keithradford** [comment]
@zthh626 I don't think this is a problem on our end. Looked at a few examples and it appears UVic and clockwork are displaying the same information. See:
![Screen Shot 2021-04-11 at 2.00.42 PM.png](https://images.zenhubusercontent.com/5f973f7c87cad5309bf82827/baf796b4-9ff1-4539-a2eb-9abdab82d954)![Screen Shot 2021-04-11 at 2.00.31 PM.png](https://images.zenhubusercontent.com/5f973f7c87cad5309bf82827/e5059706-bf89-46a5-a48e-d84fe303c829)
